### ISSUE TITLE
great sketch

### ISSUE THREAD

**Issue by rajbadri** [jeffeb3/esp8266_lights#1]
thanks for the sketch. its working nicely.
only one problem the white is not white but more like cyan
and one wish to add a dimmer to the sketch if possible

Thanks again

**Comment by jeffeb3** [comment]
I'm not sure what you mean on either account. You mean that rgb/FFFFFF isn't white? That's a hardware problem, most likely. The software treats all three channels the same.

To dim it, you can request a different value, like rgb/7F7F7F, which is half, but will be much dimmer, because of the gamma curve in the software. The software (this is Eryk's design) converts the value defined by the two characters for each channel, into a byte (0-255) and then maps it to a smaller range (0-63) and uses that value to look up a value between 0-1023. The 0-63 -> 0-1023 mapping is defined in the gamma_table. So if you as for "rgb/FFFFFF", that will be treated as 255, which is the max mapping of 63, which looks up in the gamma_table as 1023, and 1023 goes to each channel's output. If you ask for rgb/7F7F7F, that will get mapped to 31, which is is 55 in the gamma_table, which means the lights will be on for 55/1023 of the time, meaning they will be really pretty dim. Half brightness is 512, which is about the 55th element in gamma_table. To get that, you'd have to put in a 0xDC for each channel (rgb/DCDCDC). 

I'm not really sold on the gamma curve. I think it would be more useful if each channel had it's own, but tuning it would be a pain.

**Comment by andreaguiar** [comment]
Hi
I'm new to this arduino/esp8266 environment so I'm not sure if I'm doing this right...

When I try to compile with arduino ide I get this error:
'convertToInt' was not declared in this scope

I have put the constants.h and led.h in /Documents/Arduino/libraries

Thanks

**Comment by jeffeb3** [comment]
Don't put them in Libraries, just put all them in the same folder, and open the .ino. Then open the files in the same window. When all three of them are open (as different tabs) then you can try to compile it.

**Comment by jeffeb3** [comment]
Here is more info (the Multi file section especially). https://www.arduino.cc/en/Hacking/BuildProcess

**Comment by andreaguiar** [comment]
Done. But I still get 'convertToInt' was not declared in this scope

**Comment by andreaguiar** [comment]
C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:32: warning: character constant too long for its type [enabled by default]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:32: warning: multi-character character constant [-Wmultichar]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino: In function 'void loop()':

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:39: warning: large integer implicitly truncated to unsigned type [-Woverflow]

esp8266_lights:99: error: 'convertToInt' was not declared in this scope

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:38: warning: large integer implicitly truncated to unsigned type [-Woverflow]

esp8266_lights:122: error: 'convertToInt' was not declared in this scope

exit status 1
'convertToInt' was not declared in this scope

**Comment by jeffeb3** [comment]
Can you open a new issue?

**Comment by andreaguiar** [comment]
ok
